import { jsPDF } from "jspdf";
import { PlayerData, CoachSettings } from "./types";

export function generateRegistrationPDF(players: PlayerData[], settings: CoachSettings) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = 210;
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  // ---- Helper ----
  const addSection = (title: string, items: { label: string; value: string }[]) => {
    if (y > 250) {
      doc.addPage();
      y = margin;
    }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(245, 158, 11); // amber-500
    doc.text(title, margin, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(55, 65, 81); // slate-700

    items.forEach((item) => {
      const line = `${item.label}: ${item.value || "—"}`;
      if (y > 275) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin + 2, y);
      y += 5;
    });
    y += 3;
  };

  // ---- Header ----
  // Logo (if present) – small, top-left
  if (settings.logoDataUrl) {
    try {
      doc.addImage(settings.logoDataUrl, "PNG", margin, y, 20, 20);
    } catch {
      // ignore if image fails
    }
  }

  // Organization name centered
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42); // slate-950
  const orgName = settings.orgName || "Youth Sports Registration";
  const orgX = pageW / 2;
  doc.text(orgName, orgX, y + 10, { align: "center" });

  y += 16;

  // Divider line
  doc.setDrawColor(245, 158, 11);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // Coach info row
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  const coachLine = [
    settings.coachName && `Coach: ${settings.coachName}`,
    settings.coachEmail,
    settings.coachPhone && `Tel: ${settings.coachPhone}`,
    settings.teamName && `Team: ${settings.teamName}`,
  ]
    .filter(Boolean)
    .join("  |  ");
  doc.text(coachLine, margin, y);
  y += 6;

  // ---- Players Table ----
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(245, 158, 11);
  doc.text("Registered Players", margin, y);
  y += 7;

  // Table header
  doc.setFillColor(15, 23, 42);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");

  const cols = [
    { label: "#", x: margin, w: 8 },
    { label: "First Name", x: margin + 8, w: 30 },
    { label: "Last Name", x: margin + 38, w: 30 },
    { label: "Age", x: margin + 68, w: 10 },
    { label: "Pos", x: margin + 78, w: 22 },
    { label: "Jersey", x: margin + 100, w: 14 },
    { label: "Parent", x: margin + 114, w: 30 },
    { label: "Phone", x: margin + 144, w: 25 },
    { label: "Medical", x: margin + 169, w: 26 },
  ];

  // Draw header background
  doc.rect(margin, y - 2, contentW, 6, "F");

  cols.forEach((c) => {
    doc.text(c.label, c.x, y + 1);
  });

  y += 7;

  // Table rows
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);

  players.forEach((p, i) => {
    if (y > 275) {
      doc.addPage();
      y = margin;
      // Re-draw header on new page
      doc.setFillColor(15, 23, 42);
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.rect(margin, y - 2, contentW, 6, "F");
      cols.forEach((c) => doc.text(c.label, c.x, y + 1));
      y += 7;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(55, 65, 81);
    }

    const rowColor = i % 2 === 0 ? [248, 250, 252] : [241, 245, 249];
    doc.setFillColor(rowColor[0], rowColor[1], rowColor[2]);
    doc.rect(margin, y - 2, contentW, 5.5, "F");

    const row: Record<string, string> = {
      idx: String(i + 1),
      firstName: p.firstName,
      lastName: p.lastName,
      age: p.age,
      pos: p.position,
      jersey: p.jerseyNumber || "",
      parent: p.parentName || "",
      phone: p.parentPhone || "",
      medical: p.medicalNotes || "",
    };

    cols.forEach((c) => {
      const key = c.label.toLowerCase().replace(/\s+/g, "");
      doc.text(row[key] || "", c.x, y + 1);
    });

    y += 6;
  });

  // ---- Footer ----
  y = Math.max(y + 8, 270);
  doc.setDrawColor(200, 200, 210);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 4;

  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by DiamondForms · ${new Date().toLocaleDateString()}`, margin, y);

  // "FREE" watermark
  doc.setFontSize(6);
  doc.setTextColor(203, 213, 225);
  doc.text("Free tier — DiamondForms branding", pageW - margin, y, { align: "right" });

  // Save
  const filename = `registration_${settings.orgName?.replace(/\s+/g, "_") || "team"}_${Date.now()}.pdf`;
  doc.save(filename);
}